### ISSUE TITLE
Problemas con los DNS

### ISSUE THREAD

**Issue by iblancasa** [analca3/blog_files#1]
Cuando intentas acceder al blog, no se puede por el enlace "oficial": http://blog.analca3.com/
Pero por aquí sí: http://analca3.github.io/blog/

Comprueba los DNS. Puede que no se haya actualizado el servidor y tengas que esperar (hasta 24 horas)

**Comment by 29antonioac** [comment]
Perfecto entnces. Tengo los DNS de Google, así que supongo que tendrán que
actualizarlo. Ahora a arreglar los css...

**Comment by iblancasa** [comment]
¿Y has apuntado el CNAME a GitHub?

Es por eso que no funciona el CSS. Como no puede resolver el dominio, la hoja de estilos no puede cargarse desde el dominio.

**Comment by 29antonioac** [comment]
https://github.com/analca3/blog/blob/gh-pages/CNAME

Eso es lo único que tengo de CNAME en el otro repo. ¿Necesito algo más?

**Comment by iblancasa** [comment]
En tu proveedor de servicios de dominio, tienes que darle como CNAME GitHub. Mira esto https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by 29antonioac** [comment]
La verdad es que no sé de lo que me hablas xD, ¿es algo que tengo que configurar en mi pc? ¿Qué pasa con quien acceda desde fuera? Me pillas fuerísima...

**Comment by iblancasa** [comment]
No he dicho nada.

Estás intentando que la gente acceda a http://blog.analca3.com/ Para ello, primero tienes que redirigir el subdominio blog.analca3.com Pero antes, tienes que comprar el dominio analca3.com, que sé que no lo has comprado por que está libre 

En la configuración de Jekyll, donde tienes la URL, tienes que poner http://analca3.github.io/blog/ 
Si quieres que sea solo http://analca3.github.io/ tienes que ponerlo en un repo nuevo que se llame "analca3.github.io" (recuerda cambiar el repo en el que se suben los ficheros de Travis)

**Comment by 29antonioac** [comment]
Qué genio! Ahora sí funciona :D

La verdad es que me resultaba extraño que pudiera tener acceso al dominio que me diera la gana xDDDD, ya me queda todo claro :).

Gracias!
